# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarrotYard < Formula
  desc "carrot-yard cli"
  homepage "https://github.com/carrots-sh/carrot-yard"
  version "0.1.5"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.1.5/carrot-yard_0.1.5_darwin_amd64.tar.gz"
      sha256 "7c18da1f0c62c76401ee0be02cf508726d38e776d6643ab98aedb2f719ac0379"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.1.5/carrot-yard_0.1.5_darwin_arm64.tar.gz"
      sha256 "63fc12ed0841f62f8250f7d2caa2484e66214384abd2d1802115566182470a10"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.1.5/carrot-yard_0.1.5_linux_amd64.tar.gz"
      sha256 "86d974d8ae427ca348fccf82d74ea438cfd3bebb9e94e82344407dd30e9bfc8e"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.1.5/carrot-yard_0.1.5_linux_arm64.tar.gz"
      sha256 "ee9b9b2f40a7c35186fed8670b58ee6e961254372e84a685ac1d9fc462140552"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  def caveats
    <<~EOS
      carrot-yard needs a running Docker daemon.
      On macOS: install Docker Desktop (https://docs.docker.com/desktop/)
      On Linux: ensure dockerd is running (systemctl start docker)
    EOS
  end

  test do
    assert_match "carrot-yard", shell_output("#{bin}/carrot-yard --version")
  end
end
