# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarrotYard < Formula
  desc "carrot-yard cli"
  homepage "https://github.com/carrots-sh/carrot-yard"
  version "0.3.3"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.3.3/carrot-yard_0.3.3_darwin_amd64.tar.gz"
      sha256 "819f8b09ff0433fb5d95439c921d350404bd4cf3616706d373bd8be9b6acc602"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.3.3/carrot-yard_0.3.3_darwin_arm64.tar.gz"
      sha256 "156342530f5236a340d896438b7d2b68efce8089eb74a78488d5fddc3c7a42c6"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.3.3/carrot-yard_0.3.3_linux_amd64.tar.gz"
      sha256 "4fa164316fa00c585f8f185af1b267f6e3a706f213eebeb25a09f8d17984a74f"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.3.3/carrot-yard_0.3.3_linux_arm64.tar.gz"
      sha256 "63e23acb25035d92f433d195a5543fc5daddafcdb43e6fd8052254bd1a825706"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  def caveats
    <<~EOS
      carrot-yard needs a running Docker daemon.
      On macOS: install Docker Desktop (https://docs.docker.com/desktop/)
      On Linux: ensure dockerd is running (systemctl start docker)
    EOS
  end

  test do
    assert_match "carrot-yard", shell_output("#{bin}/carrot-yard --version")
  end
end
