# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CarrotYard < Formula
  desc "carrot-yard cli"
  homepage "https://github.com/carrots-sh/carrot-yard"
  version "0.2.1"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.2.1/carrot-yard_0.2.1_darwin_amd64.tar.gz"
      sha256 "bdb276d541cd68bda761b2bee49cc1ab7e07ab2b84edc592534ecfdc793d448c"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.2.1/carrot-yard_0.2.1_darwin_arm64.tar.gz"
      sha256 "e255638ce4aa3488dad6a14df63cfd0746661716bca9c9b167fda367042cbcd0"

      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.2.1/carrot-yard_0.2.1_linux_amd64.tar.gz"
      sha256 "ab1ef065027b8e48631a543ddf90fd6cb2c1053d241496032a02ac70dd636429"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/carrot-yard/releases/download/v0.2.1/carrot-yard_0.2.1_linux_arm64.tar.gz"
      sha256 "36b25a15a62e2cad651e0765f00b13f23f20ea8e9785197afc0ef9b27ab3d42e"
      define_method(:install) do
        bin.install "carrot-yard"
      end
    end
  end

  def caveats
    <<~EOS
      carrot-yard needs a running Docker daemon.
      On macOS: install Docker Desktop (https://docs.docker.com/desktop/)
      On Linux: ensure dockerd is running (systemctl start docker)
    EOS
  end

  test do
    assert_match "carrot-yard", shell_output("#{bin}/carrot-yard --version")
  end
end
