# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casa < Formula
  desc "Interactive package manager front-end that keeps your Brewfile in sync."
  homepage "https://github.com/carrots-sh/casa"
  version "0.10.1"
  license "MIT"

  depends_on "chezmoi"
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/casa/releases/download/v0.10.1/casa_0.10.1_darwin_amd64.tar.gz"
      sha256 "b63d55c07159f0aa5bce7f17958b66bf7ef142b70d5264d02a2ae90cb89458c6"

      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/casa/releases/download/v0.10.1/casa_0.10.1_darwin_arm64.tar.gz"
      sha256 "ad85d7640df0a5f66969633730e3ee7eaede45c8a12792bc0f84a66d14bb34dc"

      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v0.10.1/casa_0.10.1_linux_amd64.tar.gz"
      sha256 "d4487c2866319a1d13a72323478fe7dbefe3e22366da97e84f62b462e6740707"
      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v0.10.1/casa_0.10.1_linux_arm64.tar.gz"
      sha256 "28030f585f775f5b0c3412cec08d4e609a775c01959bce4e82f7f31d1b67a90c"
      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  def caveats
    <<~EOS
      casa drives brew, and optionally go, uv, npm, and cargo. Install whichever
      of those you use; casa shells out to them on demand.
    EOS
  end

  test do
    assert_match "casa version", shell_output("#{bin}/casa --version")
  end
end
