# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casa < Formula
  desc "Interactive package manager front-end that keeps your Brewfile in sync."
  homepage "https://github.com/carrots-sh/casa"
  version "0.5.3"
  license "MIT"

  depends_on "chezmoi"
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/casa/releases/download/v0.5.3/casa_0.5.3_darwin_amd64.tar.gz"
      sha256 "12d3765df683505fad257a9f83541441514c27764c992263b50a83a5e7a9ebef"

      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/casa/releases/download/v0.5.3/casa_0.5.3_darwin_arm64.tar.gz"
      sha256 "3a7761bb3b4cece3c4623e8de461da47026e87fe70dc04c1cbf9a7930a3b84ed"

      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v0.5.3/casa_0.5.3_linux_amd64.tar.gz"
      sha256 "fdb21738b30f8753b4d3458ad4c4d19915cfe71344f2628354f97db0eaf8598a"
      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v0.5.3/casa_0.5.3_linux_arm64.tar.gz"
      sha256 "6b4a8042403768c81cd84eff3650c62115f6bd9207703e086c28c46c766d6634"
      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  def caveats
    <<~EOS
      casa drives brew, and optionally go, uv, npm, and cargo. Install whichever
      of those you use; casa shells out to them on demand.
    EOS
  end

  test do
    assert_match "casa version", shell_output("#{bin}/casa --version")
  end
end
