# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Casa < Formula
  desc "Interactive package manager front-end that keeps your Brewfile in sync."
  homepage "https://github.com/carrots-sh/casa"
  version "2026.06.22-5"
  license "MIT"

  depends_on "chezmoi"
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/casa/releases/download/v2026.06.22-5/casa_2026.06.22-5_darwin_amd64.tar.gz"
      sha256 "0ae132905801f8b408c95033f42545db66a18f4a7dc8aaeb8f0e5f3ec65fb417"

      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/casa/releases/download/v2026.06.22-5/casa_2026.06.22-5_darwin_arm64.tar.gz"
      sha256 "695942fc056433fff7543476f0683be448e91e5e3e51c183da6b34d6fbd3f943"

      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v2026.06.22-5/casa_2026.06.22-5_linux_amd64.tar.gz"
      sha256 "f8b8fd3ac5542a06d43f59dac2d2310f63c3390c2684e6aeab9eef68ac7c1646"
      define_method(:install) do
        bin.install "casa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/casa/releases/download/v2026.06.22-5/casa_2026.06.22-5_linux_arm64.tar.gz"
      sha256 "1f589eb84f0975c37dad5185932c1258bbe055db0e9631906d246cc6a1cac0cd"
      define_method(:install) do
        bin.install "casa"
      end
    end
  end

  def caveats
    <<~EOS
      casa drives brew, and optionally go, uv, npm, and cargo. Install whichever
      of those you use; casa shells out to them on demand.
    EOS
  end

  test do
    assert_match "casa version", shell_output("#{bin}/casa --version")
  end
end
