# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hare < Formula
  desc "hare cli"
  homepage "https://github.com/carrots-sh/hare"
  version "0.1.0"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.0/hare_0.1.0_darwin_amd64.tar.gz"
      sha256 "c3bc62b42a3a9491b74efd80673a2606f5f6edc8a5bc3ed1d88ae13e0234720a"

      define_method(:install) do
        bin.install "hare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.0/hare_0.1.0_darwin_arm64.tar.gz"
      sha256 "862b27d076e19a0afacfeba115c77a4032cd7034d5ae9d2122ebb06fbab22269"

      define_method(:install) do
        bin.install "hare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.0/hare_0.1.0_linux_amd64.tar.gz"
      sha256 "4d303728d796e1a36d316ec30599830763af4106356c15d6ffe7d8155cbef5c7"
      define_method(:install) do
        bin.install "hare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.0/hare_0.1.0_linux_arm64.tar.gz"
      sha256 "9fd58445c31a1300bae9d7b7876e71f11ad1dcb6683c5bc21c562c403ce7361f"
      define_method(:install) do
        bin.install "hare"
      end
    end
  end

  def caveats
    <<~EOS
      hare needs a running Docker daemon.
      On macOS: install Docker Desktop (https://docs.docker.com/desktop/)
      On Linux: ensure dockerd is running (systemctl start docker)
    EOS
  end

  test do
    assert_match "hare", shell_output("#{bin}/hare --version")
  end
end
