# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hare < Formula
  desc "hare cli"
  homepage "https://github.com/carrots-sh/hare"
  version "0.1.1"
  license "MIT"

  depends_on "docker" => :required

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.1/hare_0.1.1_darwin_amd64.tar.gz"
      sha256 "52f4269325a0be286b6d90359fc005a5cb2a11884583dc3d2328370292b64d68"

      define_method(:install) do
        bin.install "hare"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.1/hare_0.1.1_darwin_arm64.tar.gz"
      sha256 "9d500c5c5faa7b4c89fb03c0667d3f43671d53f716a8d548d5c96ebd8b977828"

      define_method(:install) do
        bin.install "hare"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.1/hare_0.1.1_linux_amd64.tar.gz"
      sha256 "01220c04b6371bef86a8807d83df1b43e7476fe8858cf862170fc0ca00d9977f"
      define_method(:install) do
        bin.install "hare"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/carrots-sh/hare/releases/download/v0.1.1/hare_0.1.1_linux_arm64.tar.gz"
      sha256 "a7f45efa20e6f4261c8dc240ed6deecfe214741c63ac77fda370cecbc73ebc4a"
      define_method(:install) do
        bin.install "hare"
      end
    end
  end

  def caveats
    <<~EOS
      hare needs a running Docker daemon.
      On macOS: install Docker Desktop (https://docs.docker.com/desktop/)
      On Linux: ensure dockerd is running (systemctl start docker)
    EOS
  end

  test do
    assert_match "hare", shell_output("#{bin}/hare --version")
  end
end
