# This file was generated by GoReleaser. DO NOT EDIT.
cask "hare" do
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_amd64.tar.gz"
      sha256 "3ae34303d0f081f12a2cf82422cb09eb301a8632a946465d5280bc689595c217"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_arm64.tar.gz"
      sha256 "9f55a7543bb2b69cf21dbc970616f44acc4910023d63e642cb248402e3b03178"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_amd64.tar.gz"
      sha256 "0af3e99eaec434347dbcf517e25b53f3bcc78618259f583a3812d4bef1b225a5"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_arm64.tar.gz"
      sha256 "5f2904af3ee9fee39b1c834d7665799192848b7cfea15ec2d6eeb0cfb7bc2da5"
    end
  end

  name "hare"
  desc "hare cli"
  homepage "https://github.com/carrots-sh/hare"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "docker",
    ]

  binary "hare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hare"]
    end
  end

  # No zap stanza required

end
