# This file was generated by GoReleaser. DO NOT EDIT.
cask "hare" do
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_amd64.tar.gz"
      sha256 "a05d0a2370728cea9bd4626883dec45242a4daa53ad4bb85095dc6c12cfa9a32"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_arm64.tar.gz"
      sha256 "4654b0309df8f41506d89194786a0eb16f26c93a8d801998159cc998b11222e8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_amd64.tar.gz"
      sha256 "48dc468d5281e2b691de4ed166812a663bea7c09ab773c17f67605c04ab87fa3"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_arm64.tar.gz"
      sha256 "c852250ecd7db7eb6ae5337d9e0f59356f6cff10ce5c4cfd6d0bec49f46e5cbd"
    end
  end

  name "hare"
  desc "hare cli"
  homepage "https://github.com/carrots-sh/hare"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "docker",
    ]

  binary "hare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hare"]
    end
  end

  # No zap stanza required

end
