# This file was generated by GoReleaser. DO NOT EDIT.
cask "hare" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_amd64.tar.gz"
      sha256 "392aa565df52f65f9ab2936cb43a5ec543067787b06f733533a395ab41215308"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_darwin_arm64.tar.gz"
      sha256 "43ccaaf8e3e46ac0a1bd3f976e297f00e1e33450b760ffb7626d48a98a3bf974"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_amd64.tar.gz"
      sha256 "de181fd30190320245cad817be85809b20cb3b7dc89f2385ca6e967ebd0284f2"
    end
    on_arm do
      url "https://github.com/carrots-sh/hare/releases/download/v#{version}/hare_#{version}_linux_arm64.tar.gz"
      sha256 "9eca0474dfbcdfbe5394aeb056d1652438081daa42c73c11bc6f05b1263fb187"
    end
  end

  name "hare"
  desc "hare cli"
  homepage "https://github.com/carrots-sh/hare"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on cask: [
      "docker",
    ]

  binary "hare"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hare"]
    end
  end

  # No zap stanza required

end
